# Generated by Django 3.0 on 2019-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('shown', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
